# This is a config file for the bitswap-monitoring-client tool.

# Address to listen and serve prometheus metrics on.
prometheus_address: "0.0.0.0:8088"

# Specifies the path to the MaxMind GeoLite databases.
# Defaults to /usr/local/share/GeoIP if unspecified.
#geoip_database_path: "/usr/local/share/GeoIP"

# Specifies where the gateway file is located.
# In the gateway file every line should be the id of an ipfs-gateway.
# If not provided all traffic will be logged as non-gateway-traffic.
gateway_file_path: "/usr/local/share/gateways.txt"

# List of monitors to connect to.
monitors:
  - name: "local"
    address: "127.0.0.1:8181"
