# Implements an image to run the bitswap-monitoring-client tool.
# This will expose port 8088 for prometheus.
# The executable is placed in /, the config in /config/.
# The config is copied from the builder stage (and thus verbose from the sources).
# You can probably overwrite it by mounting your own config directory, I guess.

# Get some small base image to run things on.
FROM ubuntu:jammy AS runtime

# Create a system user to drop into.
# This will get some small (<1000) UID and GID, which is fine since we don't write to any files on the host.
RUN groupadd -r ipfs \
  && useradd --no-log-init -r -g ipfs ipfs \
  && mkdir -p ipfs

# Enter our working directory.
WORKDIR ipfs-tools

# Copy compiled binaries from builder.
COPY --from=ipfs-tools-builder /ipfs-tools/target/release/bitswap-monitoring-client .
COPY --from=ipfs-tools-builder /ipfs-tools/bitswap-monitoring-client/config.yaml ./config/bitswap-monitoring-client-config.yaml

# Set ownership.
RUN chown -R ipfs:ipfs ./bitswap-monitoring-client

# Set log level.
ENV RUST_LOG=info

# Expose Prometheus endpoint.
EXPOSE 8088

# Drop root.
USER ipfs

# Run the binary.
ENTRYPOINT ["./bitswap-monitoring-client","--config","./config/bitswap-monitoring-client-config.yaml"]